export default {
  common: {
    back: 'BACK',
    proceed: 'PROCEED',
    signUp: 'SIGN UP',
    dashboard: 'Dashboard',
    
  },
  errorMessage: {
    login_error: '  Login Failed! Enter valid credentials !',
    error_userId: 'Enter User Id',
    error_password: 'Enter a Password',
    error_enterFields:'Enter respective fields with valid email & mobile number!',
    error_allFields: 'Enter all fields to proceed!',
    
    error_password_match: 'Password does not match!',
    error_password_strength: 'Password must contain atleast 6 characters!',

    error_omc:'Enter a OMC ID',
    error_consumerName:'Enter a Consumer Name',
    error_issuedCyl:'Enter Item Quantity',
    error_cylinderDeposit:'Enter cylinder deposit',
    error_regulatorDeposit: 'Enter a Regulator Deposit',
    error_regulatorNumber:'Enter a Regulator Number',
    error_discount:'Enter a Discount',
    

    error_register: 'Registration failed !',
    password_changed_error: 'Error changing password',
    otp_sent: 'OTP sent sucessfully! ',
    terms: 'Please accept the terms and conditions',
    agency_error: 'Please Search an Agency to Proceed!',
    agency_search: 'Enter an LPG Distributor Id to Search!',
    delete_vehicle: 'Are you sure you want to delete this vehicle ?',
    update_vehicle: 'Error Updating Vehicle',
    error_godown: 'Error Adding Godown',
    error_fields: 'Please Enter All fields Properly!',
    some_error: 'Some Error Occured',
    delete_slot: 'Are you sure you want to delete this delivery slot ?',
    internet_error: 'Error!\nCheck your internet connection!',
    error_vehicle: 'Error Updating Vehicle',
    delete_godown: 'Are you sure you want to delete this godown ?',
    delete_item: 'Are you sure you want to delete this item ?',
    delete_staff: 'Are you sure you want to delete this staff ?',
    add_vehicle: 'Error Adding Vehicle',
    choose_picture: 'Choose Profile Image',
    all_fields: 'Enter all fields',
    error_name:'Enter a valid name',
    error_number:'Enter a valid number',
    error_email:'Enter a valid email',
    error_address:'Enter a valid address',
    error_gstin:'Enter a valid GST number',
    error_ifsc:'Enter a valid IFSC code',
    error_delivery_add: 'Start Time Should be before the End Time',
    error_pan_card: 'Enter valid PAN details',
    errror_aadhar_card: 'Enter valid aadhar details',
    required_fields: 'Enter the required fields to proceed',
    price: 'Please enter a valid item price',
    cost_price: 'Please enter a valid cost price',
    price_zero: 'Item price can not be zero',
    cost_price_zero: 'Cost price can not be zero',
    no_quantity: 'Please enter the quantity',
    no_delivery_date: 'Please select the delivery date',
    no_time_slot: 'Please select the time slot',
    no_store_selected: 'Please select a delivery address',
    no_bank_name: 'Please enter the bank name',
    no_cheque: 'Please enter the cheque or DD number',
    decimal_check: 'Please enter valid price in proper format',
    valid_item: 'Please select the item name',
    valid_trip_name: 'Please enter trip name',
    valid_trip_date: 'Please enter trip date',
    valid_trip_time: 'Please enter trip time',
    valid_trip_driver: 'Please enter driver name',
    valid_trip_delivery: 'Please enter delivery name',
    valid_trip_vehicle: 'Please enter vehicle details',
    valid_trip_startGd: 'Please enter start godown',
    valid_trip_endGd: 'Please enter end godown',
    valid_trip_agency: 'Please enter agency name',
    valid_trip_slot: 'Please enter delivery slot',
    valid_trip_boy: 'Please enter delivery boy',
    valid_item_name:'Please select the item name',
    valid_item_quantity: 'Please select the quantity',
    valid_trip_mechanic: 'Please select mechanic name',
    valid_godown: 'Please enter godown name',
    over_exceed: 'Over exceed capacity'
    
  },
  helpCenter: {
    header: 'Help Center',
    text: `Notification History records USSD, Class 0 
    (Flash) SMS, popped dialog, app
    installation, toasts and notifications
    Notification History records`,
    user_manual: 'User manual',
    training_videos: `Training videos`,
    tips: `Improvement 
         tips`,
    faq: 'FAQ',
    book_session: `Book a trainig 
      Session`,
  },
  safetyTips: {
    header: 'Safety Tips',
    text: 'Please do follow the saftey tips',
    covid : 'Covid-19 Safety Tips',
    cylinder: 'Cylinder Safety Tips'
  },
  login: {
    title_pre: '',
    title_post: 'Log In',
    user_id: 'User ID',
    password: 'Password',
    forget_password: 'Forgot Password',
    log_in: 'LOG IN',
    register_pre: 'New to MyGasOn?',
    register_post: 'Register Now',
    remember_me: 'Remember Me',
  },
  forgotPassword: {
    title_pre: 'Forgot',
    title_post: 'Password?',
    desc_page1_pre: 'Please enter your',
    desc_page1_post:
      ' to receive a verification code for resetting your password',
    registered: 'Registered',
    mobile_number: 'Mobile Number',
    req_otp: 'REQUEST OTP',
    error_message: 'Please enter correct mobile number',
    success_message: 'An OTP has been sent',
    desc_page2_pre: 'Please enter the',
    desc_page2_post: 'received.',
    otp: 'OTP ',
    waiting: 'Waiting for OTP',
    verify: 'VERIFY',
    resend: 'RESEND',
    desc_page3: 'Please enter your',
    new_pass: 'New Password',
    confirm_pass: 'Confirm Password',
    create_pass: 'CREATE PASSWORD',
   
  
  },
  changePassword: {
    title_pre: 'Change',
    title_post: 'Password?',
    desc_page3: 'Please enter your',
    new_pass: 'New Password',
    old_pass: 'Old Password',
    confirm_pass: 'Confirm Password',
    pass_mismatch: 'Password and Confirm password should be same',
    change_password:'CHANGE PASSWORD',
    change_password_header: 'Change Password',
    old_password_error: 'Enter your old password',
    pass_mismatch: 'Password and Confirm password should be same',
  },
  termsAndConditions: {
    termsConditions: 'I agree to the',
    close_btn: 'CLOSE',
    acceptAndContinue: 'Accept & Continue',
    conditions: `some very long text some very long text, some very long text some very long text some very long text some very long text some very long text`,
    agreeTerms: 'I agree to terms and conditions',
    termsConditions_btn: 'Terms & Conditions',
  },
  signup: {
    agency_msg: `Your agency have been registered successfully`,
    signup_text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore magna aliqua`,
    click_login_btn: 'Click to Login',
  },
  signup_ND: {
    agency_msg: `Your ND Customer have been registered successfully!`,
    agency_lpg_msg: `Your LPG Distributor have been registered successfully!`,

    signup_text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore magna aliqua`,
    click_login_btn: 'Click To Login',
  },
  registration: {
    title_pre: 'User',
    title_post: 'Registration',
    categories: {
      ndCustomerLabel: `Non Domestic
(Commercial) Customer`,
      ndCustomerDescription: `Notification History records USSD,
      Class 0 (Flash) SMS, popped dialog, app
      installation, toasts and
      notifications Notification History records`,
      agencyLabel: 'LPG Distributor',
      agencyDescription: `Notification History records USSD,
      Class 0 (Flash) SMS, popped dialog, app
      installation, toasts and
      notifications Notification History records`,
    },
    registerHere: 'REGISTER HERE',
    agency: {
      titlePre: 'LPG',
      titlePost: 'Distributor',
      planTitlePost: 'Plan',
      ownerDetails: {
        heading: 'Personal Information:',
        firstName: 'First Name*',
        lastName: 'Last Name*',
        mobileNumber: 'Mobile Number*',
        emailId: 'Email ID*',
      },
      agencyDetails: {
        heading: 'Organizational information:',
        organizationName: 'Organization Name*',
        agencyName: 'Agency Name*',
        phoneNumber: 'Phone Number*',
        manager: 'Manager',
        state: 'State*',
        district: 'District/City*',
      },
      agencyPlans: [
        {
          id: 'planA',
          title: 'MyGasOn Plan A',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          buttonText: 'Proceed with Plan A',
          screenName: 'RegisterAgencyPasswordSecurity',
        },
        {
          id: 'planB',
          title: 'Plan B',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          buttonText: 'Proceed with Plan B',
          screenName: 'RegisterAgencyPasswordSecurity',
        },
        {
          id: 'planC',
          title: 'Plan C',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
          buttonText: 'Proceed with Plan C',
          screenName: 'RegisterAgencyPasswordSecurity',
        },
      ],
      passwordSecurity: {
        heading: 'Password / Security:',
        userId: 'Enter Mob No. or User ID*',
        password: 'Choose Passowrd*',
        confirmPassword: 'Confirm Password*',
      },
    },
  },
  ndCustomer: {
    titlePre: 'ND',
    titlePost: 'Customer',
    personalInfo: {
      heading: 'Personal Information:',
      firstName: 'First Name*',
      lastName: 'Last Name*',
      mobileNumber: 'Mobile Number (WhatsApp)*',
      emailId: 'Email ID*',
      emailIdError: 'Invalid Email ID',
      emailId_missing: 'Email ID is missing',
      firstNameErr: 'First Name is missing',
      lastNameErr: 'Last Name is missing',
      mobileErr: 'Mobile Number is missing',
      invalid_number: `Invalid Mobile Number`,
    },
    organizationalInfo: {
      heading: 'Organizational Information:',
      organizationName: 'Organization Name*',
      organizationType: 'Organization Type*',
      omcId: 'LPG Distributor Id*',
      omcName: 'LPG Distributor Name*',
      manager: 'Owner/Manager',
      state: 'State*',
      district: 'District*',
      pincode: 'Pin Code*',
      addressLine1: 'AddressLine 1',
      addressLine2: 'AddressLine 2',
      city: 'City*',
      orgName_err: 'Organization name is missing',
      orgType_err: 'Organization Type is missing',
      pincode_err: 'Pin code is missing',
      state_err: 'State is missing',
      district_err: 'District is missing',
      city_err: 'City is missing',
    },
    passwordSecurity: {
      heading: 'Password / Security:',
      userId: 'Enter Mob No. or User ID*',
      password: 'Password*',
      confirmPassword: 'Confirm Password*',
      userId_err: 'User ID is missing',
      password_err: 'Password is missing',
      error_registration: 'Registration failed !',
    },
  },
  sideBarMenu: {
    userName: 'Mayank Mehrotra',
    userEmail: 'mayankmehrotra@gmail.com',
    dashboard: 'Dashboard',
    organisation: 'My Organisation',
    order_management: 'Order Management',
    trip_management: 'Trip Management',
    item_management: 'Item Management',
    imabalance_management: 'Imbalance Management',
    defective_management: 'Defective Management',
    payment_management: 'Payment Management',
    stock_management: 'Stock Management',
    leak_management: 'Leak Management',
    reports: 'Reports',
    pos: 'POS Management',
  },
  popUpMenu: {
    myProfile: 'My Profile',
    changeLanguage: 'Change Language',
    changePassword:'Change Password',
    calendar: 'Calendar',
    lead_generation: 'Lead Generation',
    marketing: 'Marketing & Sales',
    share: 'Share With Friend',
    help: 'Help Centre',
    safety: 'Safety Tips',
    about: 'About MyGasOn',
    logout: 'Logout',
    holiday: 'Holiday Management'
  },
  agencyHome: {
    header: 'Agency Profile',
    agency_name_prefix: 'Bihari',
    agency_name_postfix: 'Gas Service',
    agency_subtitle: 'C-56, Sector A, Aliganj, LKO. 0522-2476000',
    menu_staff: 'Staff',
    menu_vehicle: 'Vehicles',
    menu_goddown: 'Godown',
    menu_customers: 'Customers',
    menu_delivery_slots: 'Delivery Slots',
    menu_marketing: 'Marketing & Sales',
    menu_channel_partner: 'Channel Partner',
    menu_agent: 'Agent',
    menu_bank: 'Bank Information',

    menu_lead_generation: 'Lead Generation',
    suggestion: 'Suggestion',
    subject: 'Subject',
    message: 'Message',
    submit: 'Submit',
  },
  listingEmptyMessage: {
    no_staff: 'No staffs have been\n added yet.',
    no_vehicle: 'No vehicles have been\n added yet.',
    no_goddown: 'No godowns have been\n added yet.',
    no_customer: 'No customers have been\n added yet.',
    no_delivery: 'No delivery slots\n have been added yet.',
    no_days: 'No working days have been added yet',
    no_marketing: 'No marketing data\n have been added yet.',
    no_lead_generation: 'No leads have been\n added yet.',
    no_agency: 'No agencies have been\n added yet.',
    no_store: 'No stores have been\n added yet.',
    no_agent: 'No agents have been\n added yet.',
    no_channel_partner: 'No channel partners have been\n added yet.',
    no_bank: 'No banks have been\n added yet',
    no_contracts: 'No contracts have been\n added yet',
    order_contracts: 'Add some contracts to\n create an order',
    no_order_store: 'Order cannot be placed.\nPlease add an store to\n place an order',
    no_orders:'No orders yet. Create one',
    no_items: 'No items added yet. Please add one',
    no_trips: 'No trips have been added yet. Please add one',
  
   
  },
  deleteMessage: {
    delete_staff: 'Are you sure you want to delete this staff?',
    delete_store:'Are you sure you want to delete this store?',
    delete_agency:'Are you sure you want to delete this agency?',
    delete_godown: 'Are you sure you want to delete this godown?',
    delete_delivery:'Are you sure you want to delete this delivery?',
    delete_vehicle:'Are you sure you want to delete this vehicle?',
    delete_customer: 'Are you sure you want to delete this customer?',
    delete_holiday: 'Are you sure you want to delete this holiday?',
    delete_message:'Are you sure you want to delete ?',
    
    
    
    
  },
  agencyProfileEdit: {
    header: 'Agency Profile',
    agency_edit_prefix: 'Agency',
    agency_edit_postfix: 'Details',
    agency_input_name: 'Agency Name*',
    agency_input_phone: 'Phone Number*',
    agency_input_email: 'Email ID*',
    agency_input_landline: 'Landline Number',
    agency_input_address: 'Flat No. /House No. / Street',
    agency_button_geo_location: 'Geo Location',
    agency_input_address2: 'Address 2',
    agency_dropdown_district: 'District/City*',
    agency_dropdown_state: 'State*',
    agency_input_latitude: 'Latitude/Longitude',
    agency_input_pan: 'PAN',
    agency_input_gst: 'GSTIN*',
    agency_input_omc: 'Lpg Distributor*',
    agency_input_omcId: 'Lpg Distributor Code*',
    agency_logo: 'Agency Logo...',
    agency_certificate: 'Agency Incorporation Certificate',
    agency_button_proceed: 'Proceed',
    location_submit: 'Submit',
  },
  staff: {
    staff_title: 'Staff List',
    staff_invite_title: 'Invite Staff',
    staff_input_name: 'Name',
    staff_input_email: 'Email',
    staff_input_phone: 'Phone (Whats App)*',
    staff_input_org: 'Organization name*',
    staff_input_employee_type: 'Employee Type*',
    staff_invite: 'Invite',
    staff_input_name_placeholder: 'e.g. John Doe',
    staff_input_email_placeholder: 'e.g. johndoe@hotmail.com',
    staff_input_phone_placeholder: 'e.g. 0990990999',
    staff_input_org_placeholder: 'e.g. Ashok Gas',
    staff_input_employee_placeholder: 'Delivery Boy',
  },
  vehicle: {
    vehicle_title: 'Vehicle List',
    vehicle_invite_title: 'Add Vehicle',
    vehicle_input_name: 'Vehicle Name',
    vehicle_input_number: 'Vehicle Number',
    vehicle_input_capacity: 'Capacity (Cylinder)',
    vehicle_invite: 'Add Now',
    vehicle_update: 'Update Now',

    vehicle_input_name_placeholder: 'Mahindra Bolero',
    vehicle_input_number_placeholder: 'UP66 SQ 2030',
    vehicle_input_capacity_placeholder: '40',
  },
  bankProfileHeader: {
    header: 'Agency Profile',
  },
  customerProfileHome: {
    header: 'Customer Profile',
    customer_name_prefix: 'Moti',
    customer_name_postfix: 'Mahal',
    customer_subtitle:
      'c-56 Sector A, Aliganj LKO, 0522-24760000\nPhone: 011-12343445 , 011-23488927429875\nGSTIN:122341 , OMC:1234',
    menu_staff: 'Staff',
    menu_stores: 'Stores',
    menu_agency: 'Agency',
  },
  dropdownOptions: {
    staff_type: {
      store_manager: "Store Manager ",
      general_manager: 'General Manager',
      accountant: 'Accountant',
      chef_kitchen: 'Chef / Kitchen',
      godown_incharge: 'Godown Incharge / Point manager ',
      delivery_boy: 'Delivery Boy',
      driver: 'Driver',
      mechanic: 'Mechanic',
      agent: 'Agent',
      channel_partner:'Channel Partner'
      
    }
  },
  customerProfileEdit: {
    customer_edit_name_prefix: 'Customer',
    customer_edit_name_postfix: 'Details',
    customer_input_name: 'Customer Name*',
    customer_input_phone: 'Phone Number*',
    customer_input_email: 'Email ID*',
    customer_input_landline: 'Landline Number',
    customer_input_address: 'Address 1',
    customer_button_geo_location: 'Geo Location',
    customer_input_address2: 'Address 2',
    customer_dropdown_district: 'District/City*',
    customer_dropdown_state: 'State*',
    customer_input_latitude: 'Latitude/Longitude',
    customer_input_pan: 'PAN',
    customer_input_gst: 'GSTIN*',
    customer_input_omc: 'OMC*',
    customer_logo: 'Customer Picture',
    customer_certificate: 'Customer Incorporation Certificate',
    customer_button_proceed: 'Proceed',
    location_submit: 'Submit',
  },
  agentProfileEdit: {
    agent_edit_name_prefix: 'Agent',
    agent_edit_name_postfix: 'Details',
    agent_input_name: 'Agent Name*',
    customer_input_phone: 'Phone Number*',
    customer_input_email: 'Email ID*',
    customer_input_landline: 'Landline Number',
    customer_input_address: 'Address 1',
    customer_button_geo_location: 'Geo Location',
    customer_input_address2: 'Address 2',
    customer_dropdown_district: 'District/City*',
    customer_dropdown_state: 'State*',
    customer_input_latitude: 'Latitude/Longitude',
    customer_input_pan: 'PAN',
    customer_input_gst: 'GSTIN*',
    customer_input_omc: 'OMC*',
    agent_logo: 'Agent Picture',
    customer_certificate: 'Customer Incorporation Certificate',
    customer_button_proceed: 'Proceed',
    location_submit: 'Submit',
  },
  customerStore: {
    store_title: 'Store List',
    store_add: 'Add Store',
    store_input_gowdown_name: 'Store name*',
    store_input_gowdown_name_placeholder: 'eg:Moti mahal sector 21',
    store_input_gowdown_incharge_name: 'Godown Incharge name',
    store_input_gowdown_incharge_name_placeholder: 'eg:Harihar Singh Rathore',
    store_input_address: 'Address 1*',
    store_input_address2: 'Address 2*',
    store_input_address_placeholder: 'Flat no. / House no. / Street',
    store_input_latlng: 'Lattitude/Longitude',
    store_input_latlng_placeholder: 'Lattitude/Longitude',
    store_add_now: 'Add Store',
    store_update_now:'Update Store',
    
  },
  customerAgency: {
    agency_title: 'Agency List',
    search_agency_title: 'Search Agency By LPG Distributor Code',
    add_agency: 'Add Now',
    close_agency: 'Close',
    no_agency: 'No agency by this LPG Distributor Id',
  },
  bank: {
    bank_title: 'Agency List',
    add_bank: 'Save',
    add_new_bank: 'Add Bank',
    bank_deatils: 'Bank Details',
    save_payment: 'Save ',
    delete_agency:'Delete Agency',
    close_agency: 'Close',
    add: 'Add Payment Details',
    bank_input_gateway: 'Payment Gateway Unique ID ',
    bank_input_name: 'Bank Name',
    bank_input_number: 'Account Number',
    bank_ifsc: 'IFSC Code',
    bank_add: 'Save',
    bank_input_gateway_placeholder: 'e.g.',
    bank_input_name_placeholder: 'e.g. Unique Bank',
    bank_input_number_placeholder: 'e.g. 99999999999',
    bank_ifsc_placeholder: 'IFSC0002211',
    weekly: 'Weekly',
    monthly: 'Monthly',
    instantly: 'Instantly',
    select: 'Select payment details',
    invalid_ifsc: 'Enter valid IFSC code',
    no_banks: 'No banks have been\n added yet'

  },
  bankModal: {
    modal_title: 'Bank Added Succesfully !',
    modal_subtitle:
      'Bank will add further details, please contact your agency for further details',
    close_agency_modal: 'Close',
  },
  agencyModal: {
    modal_title: 'Agency Added Succesfully !',
    modal_subtitle:
      'Agency will add further details, please contact your agency for further details',
    close_agency_modal: 'Close',
  },
  godown: {
    godown_title: 'Godown List',
    godown_invite_title: 'Add Godown',
    godown_input_name: 'Godown Name*',
    godown_input_incharge: 'Godown Incharge Name',
    godown_input_type: 'Godown Type',
    godown_input_address: 'Address 1*',
    godown_button_geo_location: 'Geo Location',
    godown_input_address2: 'Address 2*',
    godown_dropdown_district: 'District/City*',
    godown_dropdown_state: 'State*',
    godown_input_latitude: 'Latitude/Longitude',
    godown_button_add: 'Add Godown',
    godown_button_update: 'Update Godown',

    location_submit: 'Submit',
  },
  customer: {
    customer_title: 'Add Contract',
    customer_add_title: '',
    search_customer: 'Search Customer',
    item_name: 'Item Name*',
    consumer_number: 'Consumer Number**',
    issued_cyl: 'Issued Cyl.*',
    issued_cylinder: 'Issued Cylinder*',
    cylinder_security: 'Cylinder Security Deposit*',
    regulator_serial: 'Regulator Serial Number*',
    regulatro_security:'Regulator Security Deposit*',
    omc_id: 'OMC Id*',
    sv_form: 'SV FORM UPLOAD',
    file_name:'File Name',
    discount: 'Discount*',
    save: 'Save',
  },
  agent: {
    agent_title: 'Agent List',
    agent_add_title: '',
    search_agent: 'Search Agent',
    item_name: 'Item Name*',
    issued_cyl: 'Issued Cyl.*',
    omc_id: 'OMC ID*',
    security_deposit: 'Security Deposit',
    discount: 'Discount*',
    save: 'Save',
  },
  channelPartner: {
    channel_partner_title: 'Channel Partner List',
    channel_partner_add_title: '',
    search_channel_partner: 'Search Channel Partner',
    item_name: 'Item Name*',
    issued_cyl: 'Issued Cyl.*',
    omc_id: 'OMC ID*',
    security_deposit: 'Security Deposit',
    discount: 'Discount*',
    save: 'Save',
  },
  delivery: {
    delivery_title: 'Delivery Slots',
    delivery_add_slot: 'Add Delivery Slot',
    delivery_start_time: 'Start Time',
    delivery_end_time: 'End Time',
    add_time: 'Add time slot now!',
    update_time:'Update time slot now'
  },
  contractCard: {
    item_name: 'Item Name:',
    issued_cyl: 'Issued Cyl:',
    omc_id: 'OMC ID:',
    security_deposit: 'Security Deposit:',
    discount: 'Discount',
  },
  cardDetails: {
    first_name: 'Moti',
    last_name: 'Mahal',
    detail_address:
      'C-56, Sector A, Aliganj, LKO. 0522-2476000Phone: 011-12345678, 011-12345678GSTIN:1234, OMC: 1234',
    card_type: 'Profile',
  },
  myProfile: {
    myprofie_prefix: 'My',
    myprofile_postfix: 'Profile',
    my_profile: 'My Profile',
  },
  profileData: {
    name: 'Sneha Malhotra',
    description: 'Sr. Cheff',
    phone: '+91-11-9987762872',
    email: 'sneha.malhotra@motimahal.com',
    phone2: '+91-11-9987762872',
    address1: 'Flat No. / House No. / Street',
    district: 'West Delhi',
    state: 'Delhi',
    omc: 'DLAFCDE9987*',
    addhar: 'Aadhar No# DDDFF45677*',
    pan: 'Pan# 8387738790390030*',
  },
  editProfile: {
    profile_name: 'Name',
    agency_manager: 'Agency Manager',
    customer_input_phone: 'Phone Number*',
    customer_input_email: 'Email ID*',
    customer_input_landline: 'Landline Number',
    customer_input_address: 'Address 1',
    customer_button_geo_location: 'Geo Location',
    customer_input_address2: 'Address 2',
    customer_dropdown_district: 'District/City*',
    customer_dropdown_state: 'State*',
    customer_input_latitude: 'Latitude/Longitude',
    customer_input_pan: 'PAN*',
    customer_input_adhar: 'Aadhar Card*',
    upload: 'Upload Picture',
    submit: 'Submit',
    choose: 'Choose Picture',
    uploading: 'Uploading Picture',
    updated: 'Picture Updated'
  },
  leadGeneration: {
    customer_type: 'Customer Type*',
    customer_name: 'Customer Name*',
    customer_person_name: 'Customer Person Name*',
    customer_category: 'Customer Category',
    phone: 'Phone Number*',
    email: 'Email ID*',
    omc: 'OMC*',
    existing_cyl_discount: 'Existing Cyl. Discount',
    cyliner_type: 'Cylinder Type',
    monthly_consumption: 'Monthly Consumption',
    in_stock_capacity: 'Cyl. in-stock Capacity',
    expected_discount: 'Expected Discount',
    payment_terms: 'Payment Terms*',
    opening_dates: 'Opening Dates*',
    create: 'Create',
    acknowledge: 'Acknowledge',
    subject: 'Subject',
    message: 'Message',
    title_prefix: 'Lead',
    title_postfix: 'Generation',
    submit: 'Submit',
  },
  leadGenerationList: {
    request_created_by: 'Request Created By:',
    created_date_time: 'Created Date/Time:',
    customer_type: 'Customer Type:',
    customer_name: 'Customer Name:',
    cyliner_type: 'Cylinder Type:',
  },
  leadGenerationFilter: {
    created_by: 'Created By*',
    date: 'Date',
    customer_type: 'Customer Type',
    item_type: 'Item Type',
    filter_title: 'Filters',
  },
  profile: {
    myProfile_submit: {
      modal_heading: 'Profile successfully Submitted!',
      modal_body_txt: 'Your profile is succesfully submitted!',
      close_btn: 'CLOSE',
      my: 'My ',
      profile: 'Profile',
      afterSubmit:
        'C-56, Sector A, Aliganj, LKO. 0522-2476000 Phone: 011-12345678, 011-12345678 GSTIN:1234, OMC: 1234',
    },
    profile_placeholders: {
      name: 'Name*',
      phone_no: 'Phone Number*',
      email: 'Email ID*',
      landline: 'Landline Number',
      address1: 'Address 1*',
      address2: 'Address 2',
      state: 'State*',
      city:'City*',
      lat_long: 'Latitude/Longitude',
      aadhar: 'Aadhar Card*',
      pan: 'PAN*',
      employeeType:'Employee Type'
    },
    err_msg: {
      name: 'Name is missing',
      phone_no: 'Phone Number is missing',
      invalid_phone_no: 'Invalid Phone Number',
      email: 'Email ID is missing',
      invalid_email: 'Invalid email',
      address1: 'Address 1 is missing',
      aadhar: 'Aadhar Card is missing',
      invalid_aadhar: 'Invalid Aadhar',
      pan: 'PAN is missing',
    },
  },
  items: {
    header: 'Item Management',
    item_txt: 'Item',
    item_management: {
      modal_heading: 'Added item successfully',
      update_heading: 'Item updated successfully',
      close_btn: 'CLOSE',
      management_txt: 'Management',
      item_placeholder: 'Item Name',
      hsn_code: 'HSN Code',
      cgst_placeholder: 'CGST %',
      sgst_placeholder: 'SGST %',
      price_placeholder: ' Item Price*',
      cost_price_placeholder: ' Cost Price*',
      submit:'SUBMIT'
    },
    item_listing: {
      listing_txt: 'Listing',
      item_column_txt: 'Item Name & Price',
    },
  },

  agentHome: {
    header: 'Agent Profile',
    agency_name_prefix: 'Bihari',
    agency_name_postfix: 'Gas Service',
    agency_subtitle: 'C-56, Sector A, Aliganj, LKO. 0522-2476000',
    agency_employee: 'Staff',
    agency_vehicle: 'Vehicles',
    agency_godown: 'Godown',
    agency_customer: 'Customers',
    agency_planDetails: 'Plan Details',
    agency_delivery: 'Delivery Slots',
    agency_suggestions: 'Suggesstion',
    agency_subject: 'Subject',
    agency_message: 'Message',
    agency_submit: 'Submit',
  },
  channelPartnerHome: {
    header: 'Channel Partner Profile',
    channel_name_prefix: 'Laxmi',
    channel_name_postfix: 'General Store',
    channel_subtitle:
      'C-56, Sector A, Aliganj, LKO. 0522-2476000 Phone: 011-12345678, 011-12345678 ',
    menu_staff: 'Staff',
    menu_stores: 'Stores',
    menu_agency: 'Agency',
  },

  orderManagment: {
    header: 'Order Managment',
    sort_by: 'SORT BY',
    sort_filter: {
      latest_tooldest: 'Date latest to old',
      old_to_latest: 'Date Old to Latest',
      qty_hightoLow: 'Qty. High To Low',
      qty_lowToHigh: 'Qty. Low To High',
    },
    filter: 'FILTERS',
    agency_item_name: 'Agency and Item Name',
    deliveryLocaiton: 'Delivery Location',
    order_status: 'Order Status',
    customer_type: 'Customer Type',
    date: 'Date',
    apply_btn: 'Apply',
    filter_tags: {
      credit_type: 'Credit Type Customer',
      date: 'Date',
      lpg_size: '19 Kg LPG Cyl.',
      created_by: 'Created by Abid Ali',
    },
    proceed: 'PROCEED',
  },
  orderCard: {
    order_number: 'Order Number',
    item_name: 'Item Name',
    item_qty: 'Item Quantity',
    deliver_time: '7:00 AM - 9:00 AM',
    delivery_date: '26 Apr',
    consumer_no: 'Consumer Number',
    order_value: 'Order Value',
    delivery_at: 'Delivery At',
    order_by: 'Order By',
    accept: 'Accepted',
    credit: 'Credit',
    change_status: 'Change Status',
    assing_trip: 'Assing to Trip',
  },
  orderError: {
    customer_name_error: 'Please select a customer name'
  },
  imbalanceCard: {
    imbalnce_number: 'Imbalance Number',
    item_name: 'Item Name',
    customer_name: 'Customer Name',
    pickUp: 'Pickup From',
    item_qty: 'Item Quantity',
    accepted: 'Accepted',
    initianted: 'Initiated',
  },
  paymentCard: {
    payment_no: 'Payment Number',
    amount: 'Amount',
    customer_name: 'Customer Name',
    payment_period: 'Payment Period',
    initiaed: 'Initiated',
    weekly: 'Weekly',
  },
  defectCard: {
    defect_no: 'Defective ID No.',
    item_name: 'Item Name',
    customer_name: 'Customer Name',
    item_qty: 'Qty.',
    exchange_from: 'Exchange From',
  },
  leakCard: {
    lekage_id: 'Leakage ID No:',
    item_name: 'Item Name',
    created_by: 'Created By',
    item_qty: 'Qty.',
    date_visit: 'Date of Visit: ',
    time_visit: 'Time of Visit: ',
  },
  changeStatus: {
    delivered_status: 'Delivered',
    assinged_status: 'Assigned',
    declined_status: 'Declined',
  },

  defectManagment: {
    header: 'Defect Managment',
    create_defect: 'Create Defective',
    agency_name: 'Agency Name',
    qty: 'Quantity',
    exchange_date: 'Exchange Date',
    adress: 'Address',
    remark: 'Remarks',
  },
  paymentManagment: {
    header: 'Payment Managment',
    create_payment: 'Create Payment',
    customer_name: 'Customer Name',
    amount: 'Amount',
    payment_period: 'Payment Period',
    submit: 'Submit',
  },
  leakManagment: {
    header: 'Leak Managment',
    create_leak: 'Create Lekage',
    agency: 'Agency Name and Item',
    qty: 'Quantity',
    store: 'Store',
    day_of_visit: 'Day of Visit',
    hh: 'HH:MM',
    am: 'AM',
    reason_of_visit: 'Reason of Visit',
    proceed: 'Proceed',
  },
  imabalanceManagement: {
    header: 'Imbalance Managment',
    customer_name: 'Customer Name',
    create_imbalance: 'Create Imbalance',
    item_no: 'Item No.',
    empty_qty: 'Empty Cyl. Quantity',
    customer_tab: 'Customer',
    employee_tab: 'Employee',
    submit: 'Submit',
  },
  tripManagment: {
    header: 'Trip Managment',
    trip_name: 'Trip Name',
    trip_date: 'Trip Date',
    trip_id: 'Trip ID No',
    trip_time: 'Trip Time',
    trip_time_slot: 'Delivery Slot',
    delivery_boy: 'Delivery Boy',
    assing_mechanic: 'Mechanic/Delivery Boy',
    inward: 'INWARD',
    outward: 'OUTWARD',
    driver: 'Driver',
    deliveryBoy: 'Delivery Boy',
    start_godown: 'Start Godown',
    end_godown: 'End Godown',
    assinged_vehicle: 'Assigned Vehicle',
    internal: 'Internal',
    accepted: 'Accepted',
    external: 'External',
    initiated: 'Intiated',
    omc_trip_driver: 'OMC Driver Name',
    omc_trip_vehicle: 'OMC Vehicle Details',
    omc_godown: 'Godown',
    agency_name: 'Agency Name',

  },
  orderDetail: {
    header: 'Order Detail',

    steps: {
      initiated: 'Initiated',
      accepted: 'Accepted',
      assinged: 'Assinged',
      out_for_delivery: 'Out for Delivery',
      delivered: 'Delivered',
      comleted: 'Completed',
    },
    changeStatus: 'Change Status',
    postponeDelivery: 'Postpone Delivery',
    cancelOrder: 'Cancel Order',
    give_compliment: 'Give a Compliment?',
    meet_expectation: 'Meets Expectations',
    performed_above_avg: 'Performed Above Average',
    above_expectation: 'Above Expectations',
    write_a_note: 'Write a thank you note',
    submit: 'Submit',
    verifyOtp: 'Verify OTP to complete order',
  },
  orderDetailCard: {
    agency_name: 'Agency Name:',
    order_number: 'Order Number:',
    ordered_by: 'Ordered By:',
    order_datetime: 'Order Date/Time:',
    item_name: 'Ordered Item Name',
    item_qty: 'Ordered Item Qty.:',
    delivery_date: 'Delivery Date:',
    delivery_slot: 'Delivery Time Slot:',
    remark: 'Remark',
    order_status: 'Order’s Payment Status:',
    delivery_type: 'Delivery/Pickup Type:',
    address: 'Address :',
    order_to_be_deliver: 'ORDER TO BE DELIVERED SOON',
  },
  chalanModal: {
    deliverQty: 'Delivered Qty.',
    recivedQty: 'Received Qty.',
    uploadChalan: 'UPLOAD CHALLAN',
    uploadOther: 'UPLOAD OTHER SLIP',
  },
  taxBillingCard: {
    sub_total: 'Sub Total (RSP)',
    discount: 'Discount',
    tax_amount: 'Taxable Amount',
    gst: 'GST (18%)',
    grand_total: 'Grand Total (inc. GST)',
  },
  acceptedOrderCard: {
    accepted_by: 'Accepted By',
    accepted_datetime: 'Accepted Date/Time:',
    accepted_remark: 'Accepted Remark:',
  },
  deliveryCallCard: {
    vehicle_model: 'Vehicle Make/Model:',
    vehice_type: 'Vehicle Type/No.:',
    deliveryboy_name: 'Delivery Boy Name:',
    call_delivery: 'Call Delivery Boy',
  },
  chalanCard: {
    recived_chalan: 'Received Challan Receipt:',
    other_slip: 'Other Slip:',
    tax_invoce: 'Tax Invoice No.:',
    download_invoice: 'View/Download Invoice',
    viewFile: 'View File',
  },
  deliverQuanity: {
    delivered: 'Delivered Qty.:',
    recived: 'Received Qty.:',
  },
  ratingModal: {
    ratingText: 'Rating and compliment successfully!',
    excellent_service: 'Excellent Service',
    overall: 'Overall Rating',
    close: 'Close',
    delete:'Delete'
  },
  failModal: {
    succesfully_cancel_order: 'Your order is successfully cancelled.',
    cancel_order: 'Cancel Order',
  },
  postponeDelivery: {
    postpone: 'Postpone Delivery',
    postpone_description:
      'If you are temporarily unavailable, please mention below:',
    delivery_date: 'Delivery Date',
    delivery_time: 'Delivery Time Slot',
    quantity: 'Quantity',
  },
  orderCreation: {
    header: 'Create Order',
    title: 'Agency & Item',
    stepper1: 'Agency & Item',
    stepper2: 'Qty. Date & Time',
    stepper3: 'Delivery Address',
    stepper4: 'Payment',
    stepper5: 'Submit Request',
    card_agency_name: 'Agency Name',
    card_item_name: 'Item Name',
    card_capacity: 'Capacity',
    remarks: 'Order Remarks-',
    quantity: 'Quantity',
    qty: 'Qty.',
    unitPrice: 'Unit Price',
    order: 'Order Remarks',
    delivery: 'Delivery',
    self_pickup: 'Self Pickup',
    delivery_address: 'Delivery Address',
    pay_now: 'Pay Now',
    pay_at_delivery: 'Pay At Delivery',
    paymentType: {
      cash: 'Cash',
      cheque: 'Cheque',
      self_deposit: 'Self Deposit / NEFT / RTGS to Bank',
    },
    proceed: 'Proceed',
    back: 'Back',
    payment_fail: 'Payment failed',
    payment_fail_desc:
      'An error was encountered while placing this order. Please try again!',
    order_placed: 'Your Order is placed successfully!',
    placing_order_for: 'Thank you for placing the order for',
    cylinderQty: 'Cylinder Qty ',
    your_order_id: 'Your order ID is ',
    to: 'to',
    paymentSuccesful: 'Your Order & Payment Request are placed successfully!',
    payment_request: 'Thank you for placing the payment request for',
    payment_id: ' Your payment ID is - ',
    bank_name: 'Bank Name',
    cheque_no: 'Cheque/DD No.*',
    utr_no: 'UTR/Reference Number',
    upload_recipt: 'UPLOAD RECEIPT',
    upload_cheque: 'UPLOAD CHEQUE',
    uploaded: 'Uploaded',
    uploading: 'Uploading',
    impersonate: 'Impersonate',
    onbehalf: 'Onbehalf',
    item_name: 'Item Name*',
    customer_name: 'Customer Name',
    submit: 'Submit'
  },
  createOrder: {
    header: 'Create Order',
  },

  tripCreation: {
    header: 'Create Trip',
    internal_trip: 'Internal Trip',
    external_trip: 'External Trip',
    omc_trip: 'OMC Trip',
    leak_trip: 'Leak Trip',
    other_agency: 'Other Agency Trip',
    stepper: {
      stepper1: 'Trip Type',
      stepper2: 'Trip Details',
      stepper3: 'Item Details',
    },
    add_item: 'Add item & qty.',
    submit: 'Submit',
    qty: 'Qty.',
    item_name: 'Item Name',
  },
  lekageDetail: {
    header: 'Lekage Detail',
    steps: {
      initiated: 'Initiated',
      accepted: 'Accepted',
      assinged: 'Assinged',
      reached: 'Reached',
      comleted: 'Completed',
    },
    change_status: 'Change Status',
    cancel_visit: 'Cancel Visit',
    postpone_visit: 'Postpone Visit',
    mechanic_visit_soon: 'MACHENIC TO BE VISITED SOON',
    reason_for_leakage: 'Reason for Leakage:',
    solution_for_leakage: 'Solution for Leakage:',
    submit: 'Submit',
    recived_rating: ' Received a rating!',
  },
  lekageDetailCard: {
    customer_name: 'Customer Name:',
    date_time: 'Date, Time:',
    created_by: 'Created By:',
    reason: 'Reason:',
    ordered_item: 'Ordered Item Name:',
    ordered_qty: 'Order ’s Item Qty.:',
    delivery_date: 'Delivery Date:',
    payment_status: 'Order’s Payment Status:',
    address: 'Address:',
  },
  addOrder: {
    header: 'Order',
    impersonate: 'impersonate',
    on_behalf: 'on behalf',
    item_name: 'Item Name*',
    quantity: 'Quantity',
    customer_name: 'Customer Name*',
    mobile_no: 'Mobile Number (WhatsApp)',
    email: 'Email',
    submit: 'Proceed',
  },
  helpCenter:{
    header: 'Help Center',
    text:`Notification History records USSD, Class 0 
    (Flash) SMS, popped dialog, app
    installation, toasts and notifications
    Notification History records`,
    user_manual: 'User manual',
    training_videos: `Training videos`,
    tips: `Improvement 
         tips`,
    faq : 'FAQ',
    book_session: `Book a training 
      Session`
  },
  aboutUs:{
    header:'About Us',
    text:`Notification History records USSD, Class 0 
    (Flash) SMS, popped dialog, app
    installation, toasts and notifications
    Notification History records. Notification History records USSD, Class 0 
    (Flash) SMS, popped dialog, app
    installation, toasts and notifications
    Notification History records`,
    rateUs:'RATE US',
    product_ver:'Product Version:',
    release_date:'Release Date',
    app_size:'App. Size:',
    suggestion:'Suggestion',
    subject:'Subject',
    message:'Message',
    submit:'SUBMIT',
    success: 'Your suggestion has been sent successfully',
    
    },
  planDetails:{
    header:'Plan Details',
    text:`Notification History records USSD, Class 0 
      (Flash) SMS, popped dialog, app
      installation, toasts and notifications
      Notification History records`,
    },
    shareWithFriends:{
      header:'Share With Friends',
      text:`You can share the details for this MyGasOn
      Application with your friends and 
      colleagues.`,
      name:'Name*',
      mobile:'Mobile Number (WhatsApp)*',
      email:'Email ID',
      omc_name:'OMC Name',
      agency_name:'Agency Name',
      submit: 'SUBMIT',
      close_btn:'CLOSE',
      success_msg:'Successfully Submitted',
    },
  loadingText: {
    loading: 'Loading...',
  },
  language: {
    header: 'Language',
  },
  agencyDashboard: {
    trip_to_close: 'Trip to be closed',
    order_created: 'Order created',
    order_accepted_not_assigned: 'Order accepted not assigned',
    pending_trip: 'Pending Trip',
    todays_trip: "Today's Trip",
    pending_order: 'Pending Order',
    todays_order: "Today's Order",
    pending_payment: 'Pending Payment',
    todays_payment: "Today's Payment",
    pending_imbalance: 'Pending Imbalance',
    todays_collection: "Today's Collection",
    defects: 'Defects',
    leaks: 'Leaks',
    stocks: 'Stocks',
    reports: 'Reports'
  },
  customerDashboard: {
    reach_status: 'Reach status... 2 Minutes',
    pending_order: 'Pending Order',
    todays_delivery: "Today's Delivery",
    pending_imbalance: 'Pending Imbalance',
    todays_collection: "Today's Collection",
    pending_payment: 'Pending Payment',
    todays_defective: "Today's Defective",
    todays_refill: "Today's Refill",
    todays_new_pos: "Today's New POS",
    bill: 'Last month bill value Rs. 60000/-'
  },
  notifications: {
    subject: 'Please enter the subject',
    suggestion: 'Please enter some suggestions',
    all_fields: 'Please enter all the fields'
  },
  pay_now:{
    title : 'MyGasOn'
  }
};
